openapi: 3.0.3
info:
  title: Reward Program API
  description: API for managing customer transactions and rewards
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
tags:
  - name: rewards
    description: APIs for Rewards Program

paths:
  /transactions:
    post:
      summary: Save a transaction
      operationId: saveTransaction
      tags:
        - rewards
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '201':
          description: Transaction saved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
    get:
      summary: Retrieve all transactions
      operationId: getTransactions
      tags:
        - rewards
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'

  /transactions/rewards:
    get:
      summary: Retrieve rewards for a customer
      operationId: getRewards
      tags:
        - rewards
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RewardResponseList'

components:
  schemas:
    RewardResponseList:
      type: array
      items:
        $ref: '#/components/schemas/RewardResponse'
    Transaction:
      type: object
      properties:
        id:
          type: string
        transactionDate:
          type: string
        customerId:
          type: string
        amount:
          type: integer
    RewardResponse:
      type: object
      properties:
        customerId:
          type: string
        totalReward:
          type: integer
        monthlyRewards:
          type: array
          items:
            type: object
            properties:
              month:
                type: string
              rewardPoint:
                type: integer